"""
weathergraph.cf_meta
=====================

CF-1.11 (Climate and Forecast) convention metadata for the WeatherGraph
inference engine.

This module defines standard names, units, and long names for every
atmospheric variable and coordinate produced by the engine, following
the UDUNITS-compatible naming required by MetPy, xCDAT, and the broader
climate-science Python ecosystem.

References
----------
- CF Conventions 1.11: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html
- UDUNITS: https://www.unidata.ucar.edu/software/udunits/
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import xarray as xr


# ── Variable-level CF attributes ──────────────────────────────────────────────
# Keys match the WeatherGraph 6-variable contract: z, q, t, u, v, w.

CF_VARIABLE_ATTRS: Dict[str, Dict[str, str]] = {
    "z": {
        "standard_name": "geopotential",
        "long_name": "Geopotential",
        "units": "m2 s-2",
    },
    "q": {
        "standard_name": "specific_humidity",
        "long_name": "Specific Humidity",
        "units": "kg kg-1",
    },
    "t": {
        "standard_name": "air_temperature",
        "long_name": "Air Temperature",
        "units": "K",
    },
    "u": {
        "standard_name": "eastward_wind",
        "long_name": "Eastward Wind Component",
        "units": "m s-1",
    },
    "v": {
        "standard_name": "northward_wind",
        "long_name": "Northward Wind Component",
        "units": "m s-1",
    },
    "w": {
        "standard_name": "lagrangian_tendency_of_air_pressure",
        "long_name": "Vertical Velocity (Pressure)",
        "units": "Pa s-1",
    },
}


# ── Coordinate CF attributes ─────────────────────────────────────────────────

CF_COORDINATE_ATTRS: Dict[str, Dict[str, str]] = {
    "latitude": {
        "standard_name": "latitude",
        "long_name": "Latitude",
        "units": "degrees_north",
        "axis": "Y",
    },
    "longitude": {
        "standard_name": "longitude",
        "long_name": "Longitude",
        "units": "degrees_east",
        "axis": "X",
    },
    "time": {
        "standard_name": "time",
        "long_name": "Forecast Valid Time",
        "axis": "T",
    },
    "level": {
        "standard_name": "air_pressure",
        "long_name": "Pressure Level",
        "units": "hPa",
        "positive": "down",
        "axis": "Z",
    },
}


# ── Global dataset attributes ────────────────────────────────────────────────

def _global_attrs(source: str = "WeatherGraph Engine") -> Dict[str, str]:
    """Return CF-compliant global dataset attributes."""
    import datetime

    return {
        "Conventions": "CF-1.11",
        "title": "WeatherGraph GNN Atmospheric Forecast",
        "institution": "WeatherGraph Project",
        "source": source,
        "history": f"{datetime.datetime.utcnow().isoformat()}Z: Generated by WeatherGraph Engine",
        "references": "Keisler, R. (2022). Forecasting Global Weather with Graph Neural Networks. arXiv:2202.07575",
    }


# ── Builder: raw tensors → CF-compliant xr.Dataset ───────────────────────────

def build_cf_dataset(
    trajectory: List[np.ndarray],
    lat: np.ndarray,
    lon: np.ndarray,
    levels: List[int],
    level_vars: List[str],
    t0: Optional[str] = None,
) -> xr.Dataset:
    """Convert a list of raw model output buffers into a CF-compliant Dataset.

    Parameters
    ----------
    trajectory : list of np.ndarray
        Each element has shape ``(1, nodes, 78)`` — one autoregressive step.
    lat : np.ndarray
        1-D latitude coordinate (descending, 90 → −90).
    lon : np.ndarray
        1-D longitude coordinate (0 → 360−Δ).
    levels : list of int
        Pressure levels in hPa (e.g. ``[50, 100, …, 1000]``).
    level_vars : list of str
        Variable short names (``['z', 'q', 't', 'u', 'v', 'w']``).
    t0 : str or None
        ISO-8601 start time.  If ``None``, ``"2000-01-01"`` is used.

    Returns
    -------
    xr.Dataset
        Dataset with dimensions ``(time, level, lat, lon)`` and full CF
        metadata on every variable and coordinate.
    """
    n_steps = len(trajectory)
    lat_count = len(lat)
    lon_count = len(lon)
    n_levels = len(levels)
    n_vars = len(level_vars)
    node_count = lat_count * lon_count

    times = pd.date_range(
        start=t0 or "2000-01-01",
        periods=n_steps,
        freq="6h",
    )

    data_vars: Dict[str, xr.DataArray] = {}

    for vi, var_name in enumerate(level_vars):
        # Collect all levels for this variable across all time steps.
        # Shape: (time, level, lat, lon)
        cube = np.empty((n_steps, n_levels, lat_count, lon_count), dtype=np.float32)

        for step_idx, output_buffer in enumerate(trajectory):
            flat = output_buffer[0, :node_count, :]  # (nodes, 78)
            grid = flat.reshape(lat_count, lon_count, n_levels * n_vars)

            for li in range(n_levels):
                ch = li * n_vars + vi
                cube[step_idx, li, :, :] = grid[:, :, ch]

        attrs = dict(CF_VARIABLE_ATTRS.get(var_name, {}))
        data_vars[var_name] = xr.DataArray(
            cube,
            dims=["time", "level", "lat", "lon"],
            attrs=attrs,
        )

    coords: Dict[str, Any] = {
        "time": ("time", times, dict(CF_COORDINATE_ATTRS["time"])),
        "level": ("level", np.array(levels, dtype=np.int32), dict(CF_COORDINATE_ATTRS["level"])),
        "lat": ("lat", np.asarray(lat, dtype=np.float64), dict(CF_COORDINATE_ATTRS["latitude"])),
        "lon": ("lon", np.asarray(lon, dtype=np.float64), dict(CF_COORDINATE_ATTRS["longitude"])),
    }

    ds = xr.Dataset(data_vars, coords=coords, attrs=_global_attrs())
    return ds


def inject_cf_attrs_netcdf(dataset, var_name: str, level: int) -> None:
    """Inject CF attributes into a netCDF4.Variable in-place.

    Parameters
    ----------
    dataset : netCDF4.Dataset
        The open NetCDF4 dataset being written.
    var_name : str
        WeatherGraph variable short name (z, q, t, u, v, w).
    level : int
        Pressure level in hPa.
    """
    cf = CF_VARIABLE_ATTRS.get(var_name, {})
    if var_name in dataset.variables:
        nc_var = dataset.variables[var_name]
        for key, value in cf.items():
            nc_var.setncattr(key, value)
        nc_var.setncattr("level_hPa", int(level))

    # Coordinate attributes
    for coord_name, coord_attrs in CF_COORDINATE_ATTRS.items():
        nc_name = coord_name
        if coord_name == "latitude":
            nc_name = "lat"
        elif coord_name == "longitude":
            nc_name = "lon"
        if nc_name in dataset.variables:
            for key, value in coord_attrs.items():
                if key not in ("standard_name", "axis") or not hasattr(dataset.variables[nc_name], key):
                    dataset.variables[nc_name].setncattr(key, value)


def inject_cf_attrs_zarr(ds_out: xr.Dataset, var_name: str, level: int) -> xr.Dataset:
    """Return a copy of *ds_out* with CF attributes injected.

    Parameters
    ----------
    ds_out : xr.Dataset
        Single-step / single-variable dataset about to be written to Zarr.
    var_name : str
        Variable short name.
    level : int
        Pressure level in hPa.

    Returns
    -------
    xr.Dataset
    """
    ds = ds_out.copy(deep=False)

    if var_name in ds:
        cf = dict(CF_VARIABLE_ATTRS.get(var_name, {}))
        cf["level_hPa"] = int(level)
        ds[var_name].attrs.update(cf)

    # Coordinate-level attributes
    for coord_name, coord_attrs in CF_COORDINATE_ATTRS.items():
        nc_name = coord_name
        if coord_name == "latitude":
            nc_name = "lat"
        elif coord_name == "longitude":
            nc_name = "lon"
        if nc_name in ds.coords:
            ds[nc_name].attrs.update(coord_attrs)

    # Global attributes
    ds.attrs.update(_global_attrs())

    return ds


def ensure_pressure_order(
    ds: xr.Dataset,
    ascending: bool = True,
    level_dim: str = "level",
) -> xr.Dataset:
    """Sort the pressure-level axis of a dataset.

    MetPy requires pressure levels sorted from **highest** (surface) to
    **lowest** (top of atmosphere) — i.e., descending.  The WeatherGraph
    model outputs levels in the order defined at training time (typically
    ascending from 50 hPa to 1000 hPa).  This helper normalises the axis
    so downstream libraries work without manual slicing.

    Parameters
    ----------
    ds : xr.Dataset
        Dataset containing a pressure-level coordinate.
    ascending : bool
        If ``True`` (default) sort 50 → 1000 hPa (ascending).
        Set ``False`` for MetPy compatibility (1000 → 50 hPa, descending).
    level_dim : str
        Name of the pressure-level dimension.

    Returns
    -------
    xr.Dataset
        A new Dataset with the level axis sorted.
    """
    if level_dim not in ds.dims:
        return ds
    return ds.sortby(level_dim, ascending=ascending)
